name: Build AutoPrint EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1. कोड clone करें
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. AutoHotkey installer डाउनलोड और इंस्टॉल करें
      - name: Install AutoHotkey 1.1 (Silent)
        run: |
          Invoke-WebRequest -Uri "https://www.autohotkey.com/download/1.1/AutoHotkey_1.1.37.02_setup.exe" -OutFile "AHKsetup.exe"
          Start-Process -FilePath .\AHKsetup.exe -ArgumentList "/S" -Wait

      # 3. .ahk को .exe में convert करें
      - name: Compile AHK to EXE
        run: |
          $compilerPath = "C:\Program Files\AutoHotkey\Compiler\Ahk2Exe.exe"
          if (!(Test-Path $compilerPath)) {
            throw "Compiler not found at $compilerPath"
          }
          & "$compilerPath" /in "autoprint.ahk" /out "autoprint.exe"

      # 4. EXE आर्टिफैक्ट upload करें
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: autoprint-exe
          path: autoprint.exe

      # 5. GitHub Release पर upload करें
      - name: Publish to Releases
        uses: softprops/action-gh-release@v2
        with:
          files: autoprint.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
