name: Build AutoPrint EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup AutoHotkey
      uses: crazy-max/ghaction-choco@v3
      with:
        args: install autohotkey.portable

    - name: Compile AHK script to EXE
      run: |
        "C:\ProgramData\chocolatey\bin\Ahk2Exe.exe" /in autoprint.ahk /out autoprint.exe

    - name: Upload EXE as artifact
      uses: actions/upload-artifact@v4
      with:
        name: autoprint
        path: autoprint.exe
