name: Build AutoHotkey EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install AutoHotkey v2 (chocolatey)
      run: choco install autohotkey.portable -y

    - name: Compile AHK script to EXE
      run: |
        $ahk2exe = "${env:ProgramFiles(x86)}\AutoHotkey\Compiler\Ahk2Exe.exe"
        if (!(Test-Path $ahk2exe)) {
          throw "Ahk2Exe.exe not found"
        }
        & "$ahk2exe" /in zebra-qr-autoprint.ahk /out zebra-qr-autoprint.exe

    - name: Upload EXE artifact
      uses: actions/upload-artifact@v4
      with:
        name: zebra-qr-autoprint-exe
        path: zebra-qr-autoprint.exe
